"""initial_schema

Revision ID: 4ad734eb5a1a
Revises: 
Create Date: 2025-12-14 16:32:12.337477

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4ad734eb5a1a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('problems',
    sa.Column('problem_id', sa.String(length=50), nullable=False),
    sa.Column('statement_latex', sa.Text(), nullable=False),
    sa.Column('statement_lean', sa.Text(), nullable=False),
    sa.Column('state_before_lean', sa.Text(), nullable=False),
    sa.Column('state_after_lean', sa.Text(), nullable=False),
    sa.Column('tactic_lean', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('problem_id')
    )
    op.create_index(op.f('ix_problems_problem_id'), 'problems', ['problem_id'], unique=False)
    op.create_table('submissions',
    sa.Column('submission_id', sa.String(length=50), nullable=False),
    sa.Column('problem_id', sa.String(length=50), nullable=False),
    sa.Column('submission_latex', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('progress', sa.Integer(), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('evaluated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['problem_id'], ['problems.problem_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('submission_id')
    )
    op.create_index(op.f('ix_submissions_problem_id'), 'submissions', ['problem_id'], unique=False)
    op.create_index(op.f('ix_submissions_submission_id'), 'submissions', ['submission_id'], unique=False)
    op.create_table('submission_results',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('submission_id', sa.String(length=50), nullable=False),
    sa.Column('verdict', sa.String(length=20), nullable=False),
    sa.Column('lean_is_valid', sa.Boolean(), nullable=False),
    sa.Column('lean_status', sa.String(length=20), nullable=False),
    sa.Column('lean_errors', sa.JSON(), nullable=True),
    sa.Column('lean_remaining_goals', sa.JSON(), nullable=True),
    sa.Column('feedback', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['submission_id'], ['submissions.submission_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_submission_results_submission_id'), 'submission_results', ['submission_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_submission_results_submission_id'), table_name='submission_results')
    op.drop_table('submission_results')
    op.drop_index(op.f('ix_submissions_submission_id'), table_name='submissions')
    op.drop_index(op.f('ix_submissions_problem_id'), table_name='submissions')
    op.drop_table('submissions')
    op.drop_index(op.f('ix_problems_problem_id'), table_name='problems')
    op.drop_table('problems')
    # ### end Alembic commands ###
